#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Comprehensive Crafting Tree Builder (521 Items Strict DAG & Semantic Logic)
--------------------------------------------------------------------------
Bu script 521 eşyanın tamamı için:
1. Mantıklı, eğlenceli ve simya doğasına uygun bileşenleri (inputs) tanımlar.
2. Kesin DAG (Directed Acyclic Graph) oluşturur; döngüleri ve ulaşılamayan düğümleri önler.
3. Her eşya için Türkçe bağlam ve bileşen açıklaması (description) üretir.
4. crafting_tree.json ve src/items/itemDefinitions.js dosyalarını günceller.
"""

import json
import re
from pathlib import Path
import networkx as nx

WORKSPACE_DIR = Path(__file__).resolve().parent.parent
ITEMS_JS_PATH = WORKSPACE_DIR / "src" / "items" / "itemDefinitions.js"
TREE_JSON_PATH = WORKSPACE_DIR / "crafting_tree.json"

# Temel Elementler
BASE_ELEMENTS = ["ates", "su", "toprak", "hava"]

def build_recipes():
    """
    521 öğenin tamamı için mantıksal, sezgisel ve tutarlı tarifler sözlüğü.
    Format:
    item_id: {
        "inputs": [id1, id2], # veya [id1, id2, id3]
        "desc": "Açıklama metni"
    }
    """
    # 1. Aşama: Temel Doğa & Element Türevleri (Tier 1)
    recipes = {
        # Temel Elementler (inputs: None)
        "buhar": {"inputs": ["ates", "su"], "desc": "Ateşin ısısıyla suyun buharlaşmasından doğan sıcak gaz kütlesi."},
        "camur": {"inputs": ["su", "toprak"], "desc": "Toprağın su ile yoğrulmasıyla oluşan yumuşak ve şekillendirilebilir balçık."},
        "lav": {"inputs": ["ates", "toprak"], "desc": "Toprağın ve kayaların aşırı yüksek sıcaklıkta erimiş hali."},
        "toz": {"inputs": ["hava", "toprak"], "desc": "Rüzgarın toprağı aşındırıp havaya savurmasıyla oluşan ince zerreler."},
        "kum": {"inputs": ["hava", "toprak"], "desc": "Kayaların ve toprağın rüzgar ile ufalanmasından doğan ince tanecikler."},
        "ruzgar": {"inputs": ["hava", "hava"], "desc": "Hava kütlelerinin basınç farkıyla hareket etmesiyle oluşan esinti."},
        "yagmur": {"inputs": ["hava", "su"], "desc": "Havadaki su buharının yoğunlaşıp yeryüzüne damlalar halinde düşmesi."},
        "enerji": {"inputs": ["ates", "hava"], "desc": "Ateş ve havanın dinamik etkileşiminden doğan saf güç."},
        "isik": {"inputs": ["ates", "hava"], "desc": "Ateşin karanlığı yaran parlak aydınlığı."},
        "tas": {"inputs": ["lav", "su"], "desc": "Ateşli lavın suyla aniden soğuyup katılaşması sonucu oluşan sert kayaç."},
        "buz": {"inputs": ["su", "hava"], "desc": "Suyun soğuk havayla donarak kristalleşmiş katı formu."},
        "alev": {"inputs": ["ates", "enerji"], "desc": "Ateşin enerjiyle parlayıp yükselen dili."},
        "duman": {"inputs": ["ates", "hava"], "desc": "Ateşin yanma sonucu havaya bıraktığı duman gazı."},
        "bulut": {"inputs": ["buhar", "hava"], "desc": "Gökyüzünde toplanan su buharı ve nem kütlesi."},
        "sis": {"inputs": ["buhar", "toprak"], "desc": "Yeryüzüne çöken serin nem ve su buharı tabakası."},
        "volkan": {"inputs": ["lav", "toprak"], "desc": "Yerin derinliklerindeki lavı püskürten dağ."},
        "yanardag": {"inputs": ["lav", "toprak"], "desc": "Ateş ve lav fışkırtan aktif volkanik dağ."},
        "gayzer": {"inputs": ["buhar", "toprak"], "desc": "Yeraltındaki sıcak su ve buharın yeryüzüne fışkırması."},
        "tufan": {"inputs": ["yagmur", "su"], "desc": "Şiddetli yağmurlar sonucu yeryüzünü kaplayan dev su taşkını."},
        "firtina": {"inputs": ["ruzgar", "enerji"], "desc": "Güçlü rüzgarların enerjiyle birleşip kasıp kavurduğu fırtına."},
        "yildirim": {"inputs": ["firtina", "enerji"], "desc": "Bulutların sürtünmesiyle gökyüzünden yere çakan dev elektrik arkı."},
        "elektrik": {"inputs": ["enerji", "yildirim"], "desc": "Yıldırım ve enerjinin kontrol edilebilir akım hali."},
        "plazma": {"inputs": ["ates", "elektrik"], "desc": "Ateşin aşırı enerji ve elektrikle iyonlaşmış dördüncü madde hali."},
        "kar": {"inputs": ["bulut", "buz"], "desc": "Bulutlardaki su damlacıklarının donarak oluşturduğu beyaz kristaller."},
        "dolu": {"inputs": ["yagmur", "buz"], "desc": "Yağmur damlalarının fırtınada donarak buz topuna dönüşmesi."},
        "cig": {"inputs": ["kar", "toprak"], "desc": "Dağlardan kayarak aşağı yuvarlanan dev kar kütlesi."},
        "buzul": {"inputs": ["buz", "buz"], "desc": "Yıllar boyunca biriken devasa donmuş buz kütlesi."},
        "buz_dagi": {"inputs": ["buzul", "su"], "desc": "Okyanusta yüzen devasa buz kütlesi, aysberg."},
        "meltem": {"inputs": ["ruzgar", "su"], "desc": "Denizden karaya doğru esen hafif ve ferahlatıcı rüzgar."},
        "hortum": {"inputs": ["ruzgar", "firtina"], "desc": "Dönen güçlü hava kolonunun yere uzanmasıyla oluşan hortum."},
        "kasirga": {"inputs": ["hortum", "su"], "desc": "Okyanus üzerinde dönerek güçlenen dev fırtına."},
        "tayfun": {"inputs": ["kasirga", "ruzgar"], "desc": "Tropik denizlerde büyük yıkım yaratan dev tayfun."},
        "girdap": {"inputs": ["su", "ruzgar"], "desc": "Suyun dairesel çekim hareketiyle oluşan derin dönence."},
        "tsunami": {"inputs": ["su", "toprak"], "desc": "Deniz tabanındaki deprem veya çöküntüyle oluşan dev dalga."},
        "deprem": {"inputs": ["toprak", "enerji"], "desc": "Yer kabuğundaki fay hatlarının kırılmasıyla oluşan sarsıntı."},
        "fay_hatti": {"inputs": ["toprak", "tas"], "desc": "Yer kabuğundaki tektonik kırık çizgisi."},
        "kul": {"inputs": ["ates", "toprak"], "desc": "Ateşin yanıp kül ettiği maddelerden geriye kalan toz."},
        "ozon": {"inputs": ["hava", "elektrik"], "desc": "Yıldırımın oksijeni iyonlaştırmasıyla oluşan ozon gazı."},
        "asit_yagmuru": {"inputs": ["duman", "yagmur"], "desc": "Havadaki gazların yağmur suyuyla birleşip asitleşmesi."},
        "aurora": {"inputs": ["isik", "hava"], "desc": "Güneş rüzgarlarının atmosferle buluşmasıyla oluşan kutup ışıkları."},

        # 2. Aşama: Doğa, Mineraller, İlk Yaşam
        "obsidyen": {"inputs": ["lav", "su"], "desc": "Lavın su ile temas edip aniden donmasıyla oluşan parlak volkanik cam."},
        "tugla": {"inputs": ["camur", "ates"], "desc": "Çamurun kalıplanıp ateşte fırınlanmasıyla elde edilen yapı gereci."},
        "cam": {"inputs": ["kum", "ates"], "desc": "Kumun yüksek sıcaklıkta eritilerek şeffaflaştırılması."},
        "metal": {"inputs": ["tas", "ates"], "desc": "Kayaçların ateşte eritilerek içindeki metalik cevherin saflaştırılması."},
        "demir": {"inputs": ["metal", "toprak"], "desc": "Yer kabuğundan çıkarılan sağlam ve dövülebilir temel metal."},
        "bakir": {"inputs": ["metal", "ates"], "desc": "Kızıl renkli, elektriği ve ısıyı mükemmel ileten yumuşak metal."},
        "bronz": {"inputs": ["bakir", "tas"], "desc": "Bakır ve diğer madenlerin eritilerek alaşımlanmış sert hali."},
        "altin": {"inputs": ["metal", "isik"], "desc": "Güneş gibi parlayan, paslanmaz en değerli sarı metal."},
        "gumus": {"inputs": ["metal", "ay"], "desc": "Ay ışığı kadar parlak ve saf beyaz değerli maden."},
        "kursun": {"inputs": ["metal", "toprak"], "desc": "Ağır, yumuşak ve gri renkli yoğun metal elementi."},
        "civa": {"inputs": ["metal", "su"], "desc": "Oda sıcaklığında sıvı halde bulunan gümüşi element."},
        "komur": {"inputs": ["toprak", "ates"], "desc": "Yerin altında karbonlaşarak yüksek enerji depolayan siyah mineral."},
        "elmas": {"inputs": ["komur", "tas"], "desc": "Kömürün aşırı yer altı basıncı altında kristalleşmiş en sert cevheri."},
        "zumrut": {"inputs": ["tas", "bitki"], "desc": "Doğanın yeşilini taşıyan ışıltılı değerli taş."},
        "yakut": {"inputs": ["tas", "ates"], "desc": "Ateşin kızıllığını içinde barındıran kıymetli korindon minerali."},
        "safir": {"inputs": ["tas", "su"], "desc": "Göklerin ve denizlerin mavisini yansıtan değerli kristal taş."},
        "ametist": {"inputs": ["tas", "enerji"], "desc": "Mistik mor rengiyle büyüleyen kuvars kristali."},
        "kehribar": {"inputs": ["recine", "tas"], "desc": "Milyonlarca yıllık ağaç reçinesinin taşlaşmış fosil hali."},
        "yesim": {"inputs": ["tas", "su"], "desc": "Uzakdoğu bilgeliğinin ve dinginliğin yeşil taşı."},
        "kuvars": {"inputs": ["kum", "enerji"], "desc": "Basınç ve enerjiyle kristalleşen şeffaf mineral."},
        "kristal": {"inputs": ["su", "tas"], "desc": "Minerallerin kusursuz geometrik yapıda katılaşmış formu."},
        "kirec": {"inputs": ["tas", "ates"], "desc": "Kalker taşının ateşte yakılmasıyla elde edilen beyaz toz."},
        "alci": {"inputs": ["kirec", "su"], "desc": "Kirecin suyla karıştırılıp kuruduğunda donan harç maddesi."},
        "cimento": {"inputs": ["kirec", "camur"], "desc": "Harç ve beton yapımında kullanılan bağlayıcı gri toz."},
        "harc": {"inputs": ["cimento", "su"], "desc": "Çimento, kum ve suyun karışımıyla oluşan bağlayıcı malzeme."},
        "beton": {"inputs": ["harc", "kum"], "desc": "Harç ve çakılın donarak kaya gibi sertleşen yapı malzemesi."},
        "granit": {"inputs": ["lav", "tas"], "desc": "Magmanın derinliklerde yavaşça soğumasıyla oluşan aşırı sert taş."},
        "mermer": {"inputs": ["kirec", "tas"], "desc": "Yüksek basınç altında başkalaşmış damarlı lüks taş."},
        "tuz": {"inputs": ["deniz", "ates"], "desc": "Deniz suyunun buharlaşmasıyla geride kalan mineral kristalleri."},
        "kukurt": {"inputs": ["volkan", "toprak"], "desc": "Yanardağ bacalarından çıkan sarı renkli yanıcı mineral."},
        "barut": {"inputs": ["kukurt", "komur"], "desc": "Kükürt, kömür ve güherçilenin patlayıcı karışımı."},
        "fosil": {"inputs": ["kemik", "toprak"], "desc": "Taşlaşmış toprak katmanlarında korunan kadim canlı kalıntısı."},

        # 3. Aşama: Canlılık, Flora, Fauna & Doğa
        "yasam": {"inputs": ["enerji", "camur"], "desc": "Çamurun enerji ve şimşek ile buluşmasından doğan ilk yaşam kıvılcımı."},
        "bakteri": {"inputs": ["yasam", "su"], "desc": "Sularda oluşan mikroskobik tek hücreli ilk canlı organizma."},
        "virus": {"inputs": ["bakteri", "toprak"], "desc": "Hücreleri enfekte edebilen mikroskobik genetik parçacık."},
        "hucre": {"inputs": ["yasam", "su"], "desc": "Tüm canlıların temel yapı taşı olan biyolojik birim."},
        "tohum": {"inputs": ["yasam", "toprak"], "desc": "İçinde yeni bir bitkinin potansiyelini taşıyan çekirdek."},
        "bitki": {"inputs": ["tohum", "su"], "desc": "Topraktan ve sudan beslenerek yeşeren fotosentetik canlı."},
        "yosun": {"inputs": ["bitki", "su"], "desc": "Nemli kayaların ve suların üzerinde yayılan ilkel yeşil bitki."},
        "ot": {"inputs": ["bitki", "toprak"], "desc": "Kırlarda boy veren taze yeşil çayır örtüsü."},
        "cimen": {"inputs": ["ot", "su"], "desc": "Yeryüzünü halı gibi kaplayan sık yeşillik tabakası."},
        "cali": {"inputs": ["cimen", "toprak"], "desc": "Kısa boylu, dallı ve sık gövdeli bodur bitki kümesi."},
        "agac": {"inputs": ["bitki", "toprak"], "desc": "Yıllar içinde gövdesi odunlaşarak göğe yükselen ulu bitki."},
        "agac_kabugu": {"inputs": ["agac", "ruzgar"], "desc": "Ağacın gövdesini dış etkenlerden koruyan sert dış katman."},
        "orman": {"inputs": ["agac", "agac"], "desc": "Sayısız ağaç ve canlının bir arada yaşadığı dev ekosistem."},
        "odun": {"inputs": ["agac", "balta"], "desc": "Ağaç gövdesinin kesilerek elde edilen sert ahşap parçası."},
        "kiymik": {"inputs": ["odun", "alet"], "desc": "Odunun yarılmasıyla ayrılan ince ve sivri ahşap parçası."},
        "recine": {"inputs": ["agac", "ates"], "desc": "Ağaçların gövdesinden sızan yapışkan ve aromatik özsu."},
        "yaprak": {"inputs": ["agac", "isik"], "desc": "Bitkilerin nefes alıp güneş ışığını besine dönüştüren organı."},
        "kok": {"inputs": ["bitki", "toprak"], "desc": "Bitkiyi toprağa bağlayan ve besin toplayan yeraltı kolları."},
        "cicek": {"inputs": ["bitki", "isik"], "desc": "Bitkilerin renkli ve mis kokulu üreme organı."},
        "gul": {"inputs": ["cicek", "ates"], "desc": "Dikenli dalları ve büyüleyici kokusuyla aşkın simgesi kırmızı çiçek."},
        "kaktus": {"inputs": ["bitki", "kum"], "desc": "Çöl kuraklığına gövdesinde su depolayarak direnen dikenli bitki."},
        "sarmasik": {"inputs": ["bitki", "duvar"], "desc": "Duvarlara ve ağaçlara dolanarak tırmanan sarılıcı yeşil bitki."},
        "bambu": {"inputs": ["bitki", "ot"], "desc": "Hafif, esnek ve son derece hızlı uzayan sert gövdeli kamış."},
        "palmiye": {"inputs": ["agac", "kum"], "desc": "Tropik sahillerde ve vahada yetişen uzun gövdeli yapraklı ağaç."},
        "mantar": {"inputs": ["camur", "yosun"], "desc": "Karanlık ve nemli orman tabanında yeşeren sporlu canlı."},
        "pamuk": {"inputs": ["bitki", "bulut"], "desc": "Tarlalarda açan yumuşacık beyaz lifli dokuma bitkisi."},
        "bugday": {"inputs": ["ot", "tohum"], "desc": "İnsanlığın temel besin kaynağı olan altın sarısı başaklı tahıl."},
        "nilufer": {"inputs": ["cicek", "su"], "desc": "Durgun göl sularının üzerinde yüzen zarif su çiçeği."},
        "cay": {"inputs": ["yaprak", "su"], "desc": "Taze çay yapraklarının kaynar suda demlenmesiyle elde edilen içecek."},
        "kahve": {"inputs": ["tohum", "ates"], "desc": "Kavrulmuş kahve çekirdeklerinin demlenmesiyle yapılan uyarıcı içecek."},
        "tutun": {"inputs": ["yaprak", "ates"], "desc": "Kurutulup yakılan aromatik yapraklı bitki türü."},
        "baharat": {"inputs": ["tohum", "ates"], "desc": "Yemeklere lezzet ve koku katan kurutulmuş bitki tozu."},
        "baharat_cesnisi": {"inputs": ["baharat", "tuz"], "desc": "Farklı baharatların tuzla harmanlanmış lezzet karışımı."},
        "nane": {"inputs": ["yaprak", "ruzgar"], "desc": "Ferahlatıcı kokusuyla bilinen şifalı yeşil ot."},

        # 4. Aşama: Hayvanlar Alemi
        "hayvan": {"inputs": ["yasam", "toprak"], "desc": "Kendi kendine hareket edebilen ve beslenen canlı organizma."},
        "solucan": {"inputs": ["camur", "yasam"], "desc": "Toprağın içinde yaşayan ve toprağı havalandıran omurgasız canlı."},
        "bocek": {"inputs": ["toprak", "yasam"], "desc": "Sert kabuklu ve çok bacaklı küçük eklembacaklı canlı."},
        "karinca": {"inputs": ["bocek", "toprak"], "desc": "Topluluk halinde yaşayan çalışkan ve güçlü minik canlı."},
        "ari": {"inputs": ["bocek", "cicek"], "desc": "Çiçeklerin nektarını toplayıp kovanında bal üreten kanatlı böcek."},
        "bal": {"inputs": ["ari", "cicek"], "desc": "Arıların çiçek özlerinden ürettiği şifalı tatlı besin."},
        "bal_kavanozu": {"inputs": ["bal", "sise"], "desc": "Saf ve altın rengi balla doldurulmuş cam kavanoz."},
        "kelebek": {"inputs": ["bocek", "cicek"], "desc": "Tırtıldan kozaya, kozadan rengarenk kanatlara dönüşen zarif canlı."},
        "orumcek": {"inputs": ["bocek", "iplik"], "desc": "Sekiz bacaklı, avını yakalamak için usta ağlar ören canlı."},
        "akrep": {"inputs": ["orumcek", "kum"], "desc": "Çöl kumlarında yaşayan, kıskançlı ve zehirli kuyruklu eklembacaklı."},
        "ipekbocegi": {"inputs": ["solucan", "yaprak"], "desc": "Dut yapraklarıyla beslenip değerli ipek kozası ören tırtıl."},
        "balik": {"inputs": ["yasam", "su"], "desc": "Solungaçlarıyla suda nefes alıp yüzen pullu omurgalı canlı."},
        "balik_eti": {"inputs": ["balik", "bicak"], "desc": "Taze balığın temizlenip dilimlenmiş eti."},
        "kurbaga": {"inputs": ["balik", "camur"], "desc": "Hem karada hem suda yaşayabilen zıplayan amfibi canlı."},
        "kertenkele": {"inputs": ["kurbaga", "kum"], "desc": "Güneş altında kayalarda ısınan çevik sürüngen canlı."},
        "yilan": {"inputs": ["solucan", "zehir"], "desc": "Ayaksız, yerde kıvrılarak sürünen zehirli ve avcı canlı."},
        "timsah": {"inputs": ["kertenkele", "su"], "desc": "Nehir ve bataklıklarda pusu kuran güçlü çeneli dev sürüngen."},
        "kaplumbaga": {"inputs": ["kertenkele", "tas"], "desc": "Sert bir kabuk taşıyan yavaş ve uzun ömürlü sürüngen."},
        "kus": {"inputs": ["yasam", "hava"], "desc": "Tüyleri ve kanatlarıyla göklerde süzülen omurgalı canlı."},
        "kus_tuyu": {"inputs": ["kus", "ruzgar"], "desc": "Kuşların gövdesini kaplayan hafif ve yumuşak tüy."},
        "tavuk": {"inputs": ["kus", "bugday"], "desc": "Evcilleştirilmiş, yumurta veren kümes kuşu."},
        "kartal": {"inputs": ["kus", "dag"], "desc": "Yüksek dağ zirvelerinde yuva yapan keskin gözlü yırtıcı kuş."},
        "sahin": {"inputs": ["kus", "ruzgar"], "desc": "Hızlı dalışlarıyla bilinen avcı yırtıcı kuş."},
        "baykus": {"inputs": ["kus", "gece"], "desc": "Karanlık gecelerde sessizce avlanan bilge gözlü gece kuşu."},
        "denizanasi": {"inputs": ["balik", "su"], "desc": "Denizlerde süzülen jelatinimsi ve dokunaçlı şeffaf canlı."},
        "ahtapot": {"inputs": ["deniz", "yasam"], "desc": "Denizlerin derinliklerinde yaşayan sekiz kollu ve kamuflaj ustası canlı."},
        "balina": {"inputs": ["balik", "okyanus"], "desc": "Okyanuslarda yüzen dünyanın en büyük memeli dev canlısı."},
        "kopekbaligi": {"inputs": ["balik", "kan"], "desc": "Keskin dişleri ve koku alma yetisiyle okyanusların tepe avcısı."},
        "yunus": {"inputs": ["balina", "su"], "desc": "Zekası ve oyuncu hareketleriyle bilinen dost canlısı deniz memelisi."},
        "denizkizi": {"inputs": ["balik", "insan"], "desc": "Efsanelere konu olan yarı insan yarı balık büyülü deniz varlığı."},
        "inek": {"inputs": ["hayvan", "cimen"], "desc": "Çiftliklerde otlayıp insanlara bol süt ve et sağlayan uysal memeli."},
        "koyun": {"inputs": ["hayvan", "ot"], "desc": "Yumuşacık yünü ve eti için beslenen sürü hayvanı."},
        "at": {"inputs": ["hayvan", "bozkir"], "desc": "Asil duruşu, gücü ve hızıyla tarihe yön veren binek hayvanı."},
        "kurt": {"inputs": ["hayvan", "orman"], "desc": "Ay ışığında uluyan, sürü halinde organize avlanan vahşi avcı."},
        "kopek": {"inputs": ["kurt", "insan"], "desc": "İnsanın en sadık dostu haline gelmiş evcil ve koruyucu hayvan."},
        "kedi": {"inputs": ["hayvan", "ev"], "desc": "Mırıltısıyla huzur veren, çevik ve bağımsız evcil avcı."},
        "aslan": {"inputs": ["kedi", "bozkir"], "desc": "Görkemli yelesi ve kükreyişiyle savanaların ve ormanların kralı."},
        "kaplan": {"inputs": ["kedi", "orman"], "desc": "Çizgili postu ve müthiş avlanma becerisiyle bilinen büyük kedi."},
        "ayi": {"inputs": ["hayvan", "magara"], "desc": "Ormanlarda ve mağaralarda yaşayan devasa cüsseli ve güçlü memeli."},
        "geyik": {"inputs": ["at", "orman"], "desc": "Görkemli boynuzlarıyla ormanın derinliklerinde süzülen zarif hayvan."},
        "sincap": {"inputs": ["fare", "agac"], "desc": "Ağaç dallarında ceviz ve palamut saklayan kabarık kuyruklu sevimli kemirgen."},
        "kemik": {"inputs": ["hayvan", "toprak"], "desc": "Omurgalı canlıların iskeletini oluşturan sert kalsiyum yapı."},
        "boynuz": {"inputs": ["hayvan", "kemik"], "desc": "Geyik veya boğaların başında çıkan sert savunma uzantısı."},
        "deri": {"inputs": ["hayvan", "bicak"], "desc": "Hayvan gövdesinden soyularak işlenen dayanıklı dış tabaka."},
        "yun": {"inputs": ["koyun", "makas"], "desc": "Koyundan kırkılan, sıcak tutan doğal yumuşak lif kütlesi."},
        "ipek": {"inputs": ["ipekbocegi", "koza"], "desc": "İpekböceğinin ördüğü eşsiz parlaklıkta ve incelikte lüks kumaş lifi."},
        "dinozor": {"inputs": ["kertenkele", "fosil"], "desc": "Milyonlarca yıl önce yeryüzüne hükmetmiş dev kadim sürüngen."},
        "ejderha": {"inputs": ["dinozor", "ates"], "desc": "Ağzından alev püskürten, pullu ve kanatlı efsanevi canavar."},

        # 5. Aşama: İnsan, Toplum, Zanaat ve Aletler
        "insan": {"inputs": ["yasam", "toprak"], "desc": "Düşünme, alet yapma ve dünyayı dönüştürme yetisine sahip varlık."},
        "i_nsan": {"inputs": ["yasam", "toprak"], "desc": "Düşünme, alet yapma ve dünyayı dönüştürme yetisine sahip varlık."},
        "alet": {"inputs": ["tas", "odun"], "desc": "İşleri kolaylaştırmak için tahta ve taştan yapılmış ilkel araç."},
        "cekic": {"inputs": ["tas", "odun"], "desc": "Nesneleri dövmek veya çakmak için saplı ağır taş/demir başlık."},
        "balta": {"inputs": ["tas", "odun"], "desc": "Ağaç kesmek ve odun yarmak için keskin başlı alet."},
        "kazma": {"inputs": ["tas", "odun"], "desc": "Toprağı ve sert kayaları kazmak için ucu sivri kazı aracı."},
        "kurek": {"inputs": ["odun", "metal"], "desc": "Toprak, kum veya karı küremek için kullanılan geniş ağızlı alet."},
        "bicak": {"inputs": ["tas", "alet"], "desc": "Kesme ve dilimleme işlemlerinde kullanılan keskin bıçak."},
        "metal_bicak": {"inputs": ["demir", "alet"], "desc": "Demirden dövülmüş son derece keskin metal bıçak."},
        "ilkel_bicak": {"inputs": ["tas", "kiymik"], "desc": "Yontulmuş çakmaktaşından yapılan ilk kesici alet."},
        "i_lkel_bicak": {"inputs": ["tas", "kiymik"], "desc": "Yontulmuş çakmaktaşından yapılan ilk kesici alet."},
        "obsidyen_bicak": {"inputs": ["obsidyen", "odun"], "desc": "Volkanik obsidyen camından yapılmış jilet kadar keskin bıçak."},
        "makas": {"inputs": ["bicak", "bicak"], "desc": "İki kesici bıçağın bir merkezde birleşmesiyle kumaş kesen aygıt."},
        "testere": {"inputs": ["metal", "bicak"], "desc": "Tırtıklı dişleriyle ahşap ve metali biçen marangoz aleti."},
        "igne": {"inputs": ["metal", "kiymik"], "desc": "Dikiş dikmek için ucu sivri ve delikli ince metal tel."},
        "ip": {"inputs": ["lif", "lif"], "desc": "Bitkisel liflerin bükülerek birleştirilmesiyle yapılan sağlam bağ."},
        "i_p": {"inputs": ["lif", "lif"], "desc": "Bitkisel liflerin bükülerek birleştirilmesiyle yapılan sağlam bağ."},
        "iplik": {"inputs": ["ip", "ip"], "desc": "Dokuma ve dikişte kullanılan ince eğrilmiş iplik."},
        "i_plik": {"inputs": ["ip", "ip"], "desc": "Dokuma ve dikişte kullanılan ince eğrilmiş iplik."},
        "halat": {"inputs": ["ip", "ip"], "desc": "Kalın ve ağır yükleri çekmek için bükülmüş güçlü urgan."},
        "kumas": {"inputs": ["iplik", "iplik"], "desc": "İpliklerin dokuma tezgahında örülmesiyle elde edilen kumaş."},
        "demir_kulce": {"inputs": ["demir", "ates"], "desc": "Yüksek fırında eritilip kalıba dökülmüş saf demir kütlesi."},
        "celik": {"inputs": ["demir", "komur"], "desc": "Demirin karbon ve kömürle dövülerek güçlendirilmiş dayanıklı hali."},
        "celik_kulce": {"inputs": ["celik", "ates"], "desc": "Dövülerek kalıplanmış sağlam çelik blok."},
        "civi": {"inputs": ["demir", "cekic"], "desc": "Ahşap ve taş parçaları birbirine tutturmaya yarayan sivri metal."},
        "vida": {"inputs": ["civi", "alet"], "desc": "Dönerek ahşaba veya metale kenetlenen yivli bağlantı elemanı."},
        "cark": {"inputs": ["odun", "tekerlek"], "desc": "Dönme hareketini ileten dişli ahşap tekerlek mekanizması."},
        "disli": {"inputs": ["metal", "cark"], "desc": "Makinelerde gücü aktaran hassas kesilmiş metal dişli."},
        "disli_cark": {"inputs": ["disli", "cark"], "desc": "Mekanik sistemlerin kalbini oluşturan dişli takımı."},
        "tekerlek": {"inputs": ["odun", "alet"], "desc": "Dönerek hareketi ve taşımayı devrimleştiren dairesel icat."},
        "el_arabasi": {"inputs": ["tekerlek", "odun"], "desc": "Yükleri taşımak için tek tekerlekli insan gücüyle çalışan araç."},
        "yay": {"inputs": ["odun", "ip"], "desc": "Esnek ahşap ve gergin kirişten oluşan menzilli fırlatıcı."},
        "ok": {"inputs": ["yay", "kiymik"], "desc": "Ucu sivri metal başlıklı, yayla fırlatılan hedef oku."},
        "kilic": {"inputs": ["celik", "cekic"], "desc": "Demircinin örs üzerinde döverek şekillendirdiği keskin çelik kılıç."},
        "mizrak": {"inputs": ["odun", "bicak"], "desc": "Uzun ahşap bir sapın ucuna takılan sivri metal mızrak."},
        "kalkan": {"inputs": ["odun", "demir"], "desc": "Savaşta darbeleri savuşturmak için taşınan koruyucu levha."},
        "ahsap_kalkan": {"inputs": ["odun", "deri"], "desc": "Hafif ve çevik ahşaptan yapılmış deri kaplı siperlik."},
        "demir_kalkan": {"inputs": ["demir", "kalkan"], "desc": "Ağır ve geçit vermez yekpare demir savunma kalkanı."},
        "zirh": {"inputs": ["deri", "metal"], "desc": "Vücudu silahlardan korumak için giyilen zırhlı donanım."},
        "deri_zirh": {"inputs": ["deri", "ip"], "desc": "Sertleştirilmiş deriden yapılmış hafif ve esnek savaş yeleği."},
        "demir_zirh": {"inputs": ["demir_kulce", "zirh"], "desc": "Şövalyeleri koruyan dövme demirden gövde zırhı."},
        "migfer": {"inputs": ["demir", "cekic"], "desc": "Başı darbelerden korumak için tasarlanmış sağlam miğfer kaskı."},
        "gurz": {"inputs": ["odun", "demir"], "desc": "Düşman zırhlarını ezmek için kullanılan ağır başlıklı topuz."},
        "mancinik": {"inputs": ["odun", "halat"], "desc": "Kale surlarını yıkmak için dev kayalar fırlatan kuşatma motoru."},
        "top": {"inputs": ["barut", "demir"], "desc": "Barut patlamasıyla demir gülleler fırlatan ağır savaş topu."},
        "tufek": {"inputs": ["top", "odun"], "desc": "Omuzdan ateşlenen menzilli barutlu piyade tüfeği."},
        "tabanca": {"inputs": ["tufek", "metal"], "desc": "Tek elle kullanılabilen kompakt barutlu ateşli silah."},
        "bomba": {"inputs": ["barut", "demir"], "desc": "Fitili ateşlendiğinde infilak eden yıkıcı patlayıcı aygıt."},
        "dinamit": {"inputs": ["barut", "kum"], "desc": "Madencilikte kayaları parçalamak için kullanılan nitrogliserinli çubuk."},
        "barut_ficisi": {"inputs": ["barut", "odun"], "desc": "Büyük patlamalar yaratmak için doldurulmuş barut dolu ahşap fıçı."},
        "mesale": {"inputs": ["odun", "ates"], "desc": "Ucu reçineli bezle sarılıp yakılan elde taşınan aydınlatma aracı."},
        "kandil": {"inputs": ["camur", "ates"], "desc": "İçinde yağ yakılarak ışık veren ilkel pişmiş toprak lamba."},
        "mum": {"inputs": ["bal", "ip"], "desc": "Balmumu veya parafinin fitille yakılarak aydınlattığı mum."},
        "fener": {"inputs": ["mum", "cam"], "desc": "Rüzgardan etkilenmemesi için cam kafes içine konmuş ışık kaynağı."},
        "kilit": {"inputs": ["demir", "anahtar"], "desc": "Kapıları ve sandıkları güvenle kilitleyen mekanik düzenek."},
        "anahtar": {"inputs": ["demir", "alet"], "desc": "Kilitli mekanizmaları açmak için özel dişli metal parça."},
        "zincir": {"inputs": ["demir", "demir"], "desc": "Birbirine geçmiş demir halkalardan oluşan kopmaz bağ."},
        "comlek": {"inputs": ["camur", "ates"], "desc": "Killi çamurun çömlekçi çarkında şekillendirilip pişirilmesi."},
        "seramik": {"inputs": ["comlek", "cam"], "desc": "Sırlanarak fırınlanmış su geçirmez pürüzsüz toprak kap."},
        "porselen": {"inputs": ["seramik", "kirec"], "desc": "Beyaz kaolinden üretilen zarif, ince ve dayanıklı mutfak eşyası."},
        "kazan": {"inputs": ["demir", "ates"], "desc": "İçinde yemek veya iksir kaynatılan büyük demir kap."},
        "sise": {"inputs": ["cam", "ates"], "desc": "Sıvıları saklamak için üflenerek şekillendirilmiş cam kap."},

        # 6. Aşama: Tarım, Yiyecek, İçecek & Yaşam
        "tarim": {"inputs": ["insan", "bitki"], "desc": "Toprağı işleyerek bitki ve tahıl üretme zanaatı."},
        "un": {"inputs": ["bugday", "tas"], "desc": "Buğday tanelerinin değirmen taşında öğütülmesiyle elde edilen toz."},
        "hamur": {"inputs": ["un", "su"], "desc": "Unun su ve tuzla yoğrulmasıyla oluşan yumuşak kıvam."},
        "maya": {"inputs": ["hamur", "bakteri"], "desc": "Hamuru kabartan ve fermantasyonu başlatan canlı kültür."},
        "ekmek": {"inputs": ["hamur", "ates"], "desc": "Yoğrulmuş hamurun fırında nar gibi pişirilmiş temel hali."},
        "sut": {"inputs": ["inek", "cimen"], "desc": "İnekten sağılan taze, kalsiyum dolu beyaz besleyici sıvı."},
        "peynir": {"inputs": ["sut", "bakteri"], "desc": "Sütün mayalanıp süzülmesiyle elde edilen lezzetli gıda."},
        "yogurt": {"inputs": ["sut", "maya"], "desc": "Ilık sütün yoğurt mayasıyla fermante edilerek katılaştırılması."},
        "tereyagi": {"inputs": ["sut", "alet"], "desc": "Süt kaymağının yayıkta dövülmesiyle toplanan saf yağ."},
        "yumurta": {"inputs": ["tavuk", "tohum"], "desc": "Tavuğun yumurtladığı protein zengini kabuklu besin."},
        "et": {"inputs": ["hayvan", "bicak"], "desc": "Beslenmek için hazırlanan taze hayvansal et."},
        "kavurma": {"inputs": ["et", "ates"], "desc": "Kendi yağında kavrularak pişirilen lezzetli et."},
        "kavrulmus_et": {"inputs": ["et", "ates"], "desc": "Ateşte iyice pişirilip mühürlenmiş nefis et porsiyonu."},
        "sosis": {"inputs": ["et", "baharat"], "desc": "Kıyılmış baharatlı etin kılıflara doldurulması."},
        "pastirma": {"inputs": ["et", "baharat"], "desc": "Çemen ve baharatlarla kurutulup olgunlaştırılmış geleneksel et."},
        "havyar": {"inputs": ["balik", "tuz"], "desc": "Değerli mersin balığından elde edilen lüks tuzlu balık yumurtası."},
        "seker": {"inputs": ["bitki", "ates"], "desc": "Şeker pancarı veya kamışından kaynatılarak kristalleştirilen tatlandırıcı."},
        "alkol": {"inputs": ["meyve", "maya"], "desc": "Şekerli meyvelerin fermantasyonuyla oluşan sarhoş edici sıvı."},
        "sarap": {"inputs": ["uzum", "maya"], "desc": "Ezilmiş üzüm suyunun fıçılarda fermente edilmesiyle yapılan içki."},
        "bira": {"inputs": ["bugday", "su"], "desc": "Arpa maltı ve şerbetçiotunun mayalanmasıyla yapılan köpüklü içecek."},
        "sirke": {"inputs": ["sarap", "hava"], "desc": "Alkolün asetik asit bakterileriyle ekşitilmiş doğal koruyucu hali."},
        "zeytin": {"inputs": ["agac", "tarim"], "desc": "Akdeniz ikliminde yetişen şifalı ve yağlı ağaç meyvesi."},
        "zeytinyagi": {"inputs": ["zeytin", "tas"], "desc": "Zeytinlerin taş baskıda sıkılmasıyla elde edilen altın sıvı."},
        "elma": {"inputs": ["agac", "cicek"], "desc": "Ağaç dallarından sarkan sulu, tatlı ve kırmızı meyve."},
        "armut": {"inputs": ["agac", "su"], "desc": "Gövdesi konik, içi sulu ve tatlı lezzetli kış meyvesi."},
        "uzum": {"inputs": ["sarmasik", "gunes"], "desc": "Salkım salkım sarkan, taze veya kurutularak yenen tatlı meyve."},
        "muz": {"inputs": ["agac", "gunes"], "desc": "Tropik iklimde yetişen yumuşak ve potasyum zengini sarı meyve."},
        "portakal": {"inputs": ["agac", "gunes"], "desc": "Turunçgiller familyasından C vitamini deposu sulu kış meyvesi."},
        "limon": {"inputs": ["agac", "asit"], "desc": "Ekşi tadı ve ferahlatıcı kokusuyla yemeklere katılan sarı meyve."},
        "karpuz": {"inputs": ["tarim", "su"], "desc": "Yaz aylarında serinleten içi kıpkırmızı ve çekirdekli dev bostan meyvesi."},
        "cilek": {"inputs": ["bitki", "seker"], "desc": "Kırmızı rengi ve mis kokusuyla sevilen lezzetli orman meyvesi."},
        "findik": {"inputs": ["agac", "toprak"], "desc": "Sert kabuğun içinde saklanan yağlı ve besleyici lezzetli yemiş."},
        "ceviz": {"inputs": ["agac", "kemik"], "desc": "Beyne benzeyen kıvrımlı yapısıyla bilinen sert kabuklu kuruyemiş."},
        "badem": {"inputs": ["agac", "tas"], "desc": "İlkbaharda çiçek açan ağacın lezzetli ve şifalı sert çekirdeği."},
        "patates": {"inputs": ["kok", "toprak"], "desc": "Toprağın altında yetişen nişasta zengini temel yumru sebze."},
        "domates": {"inputs": ["bitki", "gunes"], "desc": "Kırmızı rengi ve sulu yapısıyla sofraların vazgeçilmezi sebze."},
        "biber": {"inputs": ["bitki", "ates"], "desc": "Acı veya tatlı çeşitleriyle yemeklere lezzet katan taze sebze."},
        "sogan": {"inputs": ["kok", "toprak"], "desc": "Kat kat zarlarıyla doğranırken göz yaşartan lezzet kaynağı sebze."},
        "sarimsak": {"inputs": ["sogan", "ilac"], "desc": "Doğal antibiyotik olarak bilinen keskin kokulu şifa deposu."},
        "misir": {"inputs": ["tarim", "gunes"], "desc": "Koçanları üzerinde altın sarısı taneleri olan verimli tahıl."},
        "pirinc": {"inputs": ["tarim", "su"], "desc": "Suyla dolu çeltik tarlalarında yetişen temel Uzakdoğu tahılı."},
        "cikolata": {"inputs": ["kakao", "seker"], "desc": "Kakao çekirdeklerinin süt ve şekerle işlenmesiyle yapılan nefis tatlı."},
        "pasta": {"inputs": ["hamur", "seker"], "desc": "Krema, meyve ve şekerle süslenmiş özel kutlama tatlısı."},
        "kurabiye": {"inputs": ["un", "tereyagi"], "desc": "Fırında gevrek pişirilmiş tereyağlı ve lezzetli atıştırmalık."},
        "dondurma": {"inputs": ["sut", "buz"], "desc": "Süt ve meyvelerin dondurularak çırpılmasıyla yapılan serin tatlı."},
        "meyve_suyu": {"inputs": ["meyve", "su"], "desc": "Taze sıkılmış meyvelerin leziz ve vitaminli içeceği."},
        "recel": {"inputs": ["meyve", "seker"], "desc": "Meyvelerin şekerle kaynatılarak kavanozlara doldurulmuş hali."},
        "salca": {"inputs": ["domates", "gunes"], "desc": "Domateslerin ezilip güneşte kurutularak yoğunlaştırılmış ezmesi."},
        "corba": {"inputs": ["et", "su"], "desc": "Sebze, et ve baharatların kaynatılmasıyla yapılan sıcacık içecek yemek."},

        # 7. Aşama: Bilim, Teknoloji, Sanayi & İcatlar
        "bilim": {"inputs": ["insan", "kitap"], "desc": "Evrenin işleyişini anlama ve kanıtlara dayalı bilgi üretme disiplini."},
        "enerji": {"inputs": ["ates", "hava"], "desc": "İş yapabilme kapasitesi ve fiziksel güç kaynağı."},
        "isik": {"inputs": ["ates", "hava"], "desc": "Ateşin karanlığı aydınlatan foton ışıması."},
        "golge": {"inputs": ["isik", "insan"], "desc": "Işığın bir cisim tarafından engellenmesiyle arkasında oluşan karanlık alan."},
        "ayna": {"inputs": ["cam", "gumus"], "desc": "Camın arkasına gümüş kaplanarak görüntü yansıtması sağlanan eşya."},
        "mercek": {"inputs": ["cam", "alet"], "desc": "Işığı kırarak nesneleri büyüten veya odaklayan kavisli optik cam."},
        "prizma": {"inputs": ["cam", "isik"], "desc": "Beyaz ışığı kırarak gökkuşağı renklerine ayıran üçgen optik cam."},
        "prizma_tasi": {"inputs": ["prizma", "kristal"], "desc": "Işığı büyülü şekilde büken ve yansıtan prizmatik kristal taş."},
        "lazer": {"inputs": ["isik", "kristal"], "desc": "Tek dalga boyunda yoğunlaştırılmış güçlü ışık demeti."},
        "gokkusagi": {"inputs": ["yagmur", "gunes"], "desc": "Güneş ışığının yağmur damlalarında kırılarak oluşturduğu 7 renkli yay."},
        "radyasyon": {"inputs": ["enerji", "uranyum"], "desc": "Kararsız atom çekirdeklerinden yayılan yüksek enerjili parçacıklar."},
        "manyetizma": {"inputs": ["demir", "elektrik"], "desc": "Elektrik akımlarının veya manyetik minerallerin yarattığı çekim alanı."},
        "miknatis": {"inputs": ["demir", "manyetizma"], "desc": "Demir ve benzeri metalleri çeken manyetik kutuplu nesne."},
        "pusula": {"inputs": ["miknatis", "cam"], "desc": "Manyetik iğnesiyle kuzeyi göstererek yol bulmayı sağlayan navigasyon aleti."},
        "saat": {"inputs": ["disli", "kum"], "desc": "Zamanın akışını hassas şekilde ölçen mekanik çarklı aygıt."},
        "gunes_saati": {"inputs": ["golge", "tas"], "desc": "Güneşin konumuyla gölgenin hareketini izleyerek zamanı gösteren düzenek."},
        "kum_saati": {"inputs": ["cam", "kum"], "desc": "İki cam fanus arasında ince kumun akışıyla süreyi ölçen araç."},
        "termometre": {"inputs": ["cam", "civa"], "desc": "Cıvanın genleşmesiyle sıcaklık derecesini ölçen bilimsel alet."},
        "barometre": {"inputs": ["cam", "hava"], "desc": "Hava basıncını ölçerek hava durumunu tahmin eden gösterge."},
        "teleskop": {"inputs": ["mercek", "tup"], "desc": "Uzak yıldızları ve gezegenleri yakından incelemeyi sağlayan gök dürbünü."},
        "mikroskop": {"inputs": ["mercek", "isik"], "desc": "Gözle görülmeyen mikroskobik mikropları ve hücreleri büyüterek gösteren cihaz."},
        "pil": {"inputs": ["metal", "asit"], "desc": "Kimyasal enerjiyi elektrik enerjisine dönüştürüp depolayan küçük güç kaynağı."},
        "aku": {"inputs": ["pil", "kursun"], "desc": "Araçlar için yüksek kapasiteli şarj edilebilir elektrik akümülatörü."},
        "jenerator": {"inputs": ["miknatis", "buhar_motoru"], "desc": "Mekanik hareketi elektrik enerjisine çeviren güçlü santral makinesi."},
        "dinamolu_fener": {"inputs": ["fener", "dinamo"], "desc": "Elde çevrilen dinamo mekanizmasıyla pil olmadan ışık veren fener."},
        "buhar_motoru": {"inputs": ["buhar", "kazan"], "desc": "Buharın basıncını mekanik piston hareketine dönüştüren Sanayi Devrimi motoru."},
        "icten_yanmali_motor": {"inputs": ["buhar_motoru", "petrol"], "desc": "Yakıtın silindir içinde patlamasıyla güç üreten otomobil motoru."},
        "i_cten_yanmali_motor": {"inputs": ["buhar_motoru", "petrol"], "desc": "Yakıtın silindir içinde patlamasıyla güç üreten otomobil motoru."},
        "elektrik_motoru": {"inputs": ["elektrik", "miknatis"], "desc": "Elektrik enerjisini kesintisiz dönme hareketine çeviren sessiz motor."},
        "turbin": {"inputs": ["ruzgar", "jenerator"], "desc": "Akışkanların geçişiyle dönerek elektrik üreten dev kanatlı çark."},
        "ruzgar_gulu": {"inputs": ["ruzgar", "cark"], "desc": "Rüzgarın yönünü ve şiddetini gösteren fırıldak çarkı."},
        "su_degirmeni": {"inputs": ["su", "degirmen"], "desc": "Akan suyun gücüyle dönerek un öğüten su çarkı."},
        "yel_degirmeni": {"inputs": ["ruzgar", "degirmen"], "desc": "Rüzgarın kanatları çevirmesiyle tahıl öğüten veya su pompalayan kule."},
        "gunes_paneli": {"inputs": ["silikon", "isik"], "desc": "Güneş fotonlarını doğrudan temiz elektrik akımına çeviren fotovoltaik panel."},
        "telgraf": {"inputs": ["elektrik", "tel"], "desc": "Mors alfabesiyle elektrik sinyalleri gönderen ilk uzak iletişim cihazı."},
        "telefon": {"inputs": ["telgraf", "ses"], "desc": "İnsan sesini kablolar üzerinden uzaklara ileten iletişim devrimi."},
        "radyo": {"inputs": ["elektrik", "hava"], "desc": "Elektromanyetik dalgalarla havadan ses ve müzik yayını alan cihaz."},
        "radar": {"inputs": ["radyo", "anten"], "desc": "Radyo dalgaları fırlatarak uzaktaki cisimlerin yerini ve hızını tespit eden sistem."},
        "televizyon": {"inputs": ["radyo", "cam"], "desc": "Görüntü ve sesi ekranında birleştirip evlere sunan yayın alıcısı."},
        "kamera": {"inputs": ["mercek", "film"], "desc": "Işığı yakalayarak anları ve hareketli görüntüleri kaydeden cihaz."},
        "fotograf": {"inputs": ["kamera", "kagit"], "desc": "Gümüş tuzu ve ışıkla kağıda basılmış dondurulmuş an görüntüsü."},
        "sinema": {"inputs": ["fotograf", "isik"], "desc": "Peş peşe oynatılan karelerle dev perdede canlanan hareketli film sanatı."},
        "hesap_makinesi": {"inputs": ["disli", "mantik"], "desc": "Matematiksel işlemleri anında ve hatasız yapan dijital hesap cihazı."},
        "bilgisayar": {"inputs": ["mikrocip", "elektrik"], "desc": "Milyarlarca mantıksal veriyi saniyeler içinde işleyen akıllı elektronik beyin."},
        "mikrocip": {"inputs": ["silikon", "elektrik"], "desc": "Milyonlarca transistör içeren minyatür entegre devre yongası."},
        "yapay_zeka": {"inputs": ["bilgisayar", "mantik"], "desc": "Öğrenme, analiz ve karar verme yetisine sahip ileri düzey yazılım zekası."},
        "robot": {"inputs": ["bilgisayar", "metal"], "desc": "Programlanabilir mekanik kolları ve sensörleriyle çalışan yapay varlık."},
        "internet": {"inputs": ["bilgisayar", "bilgisayar"], "desc": "Dünyadaki tüm bilgisayarları birbirine bağlayan devasa küresel bilgi ağı."},
        "i_nternet": {"inputs": ["bilgisayar", "bilgisayar"], "desc": "Dünyadaki tüm bilgisayarları birbirine bağlayan devasa küresel bilgi ağı."},
        "uydu": {"inputs": ["roket", "radyo"], "desc": "Dünya yörüngesinde dönerek haberleşme ve gözlem yapan uzay aracı."},
        "roket": {"inputs": ["barut", "metal"], "desc": "Yakıtın arkadan püskürmesiyle yerçekimini yenip uzaya fırlayan araç."},
        "uzay_gemisi": {"inputs": ["roket", "bilgisayar"], "desc": "İnsanları ve yükleri yıldızlararası boşlukta taşıyan yüksek teknolojili araç."},
        "buhar_jeneratoru": {"inputs": ["buhar", "jenerator"], "desc": "Buhar basıncını elektrik enerjisine dönüştüren termik ünite."},
        "plazma_tufegi": {"inputs": ["tufek", "plazma"], "desc": "Aşırı sıcak plazma enerjisi mermileri sıkan bilim kurgu silahı."},
        "tesla_bobini": {"inputs": ["elektrik", "bobin"], "desc": "Havaya devasa şimşekler ve kablosuz elektrik yayan rezonans transformatörü."},
        "hologram_kupu": {"inputs": ["lazer", "kristal"], "desc": "Işık kırılmasıyla 3 boyutlu hareketli görüntüler yansıtan fütüristik küp."},
        "yercekimsiz_platform": {"inputs": ["manyetizma", "plazma"], "desc": "Manyetik itme gücüyle havada asılı duran anti-yerçekimi platformu."},
        "biyonik_kol": {"inputs": ["robot", "insan"], "desc": "Düşünce sinyalleriyle hareket eden protez biyonik mekanik kol."},
        "siber_kristal": {"inputs": ["kristal", "mikrocip"], "desc": "Kuantum verilerini ışık hızında depolayan siber optik kristal."},

        # 8. Aşama: Medeniyet, Yapılar, Ulaşım, Sanat & Sosyoloji
        "aile": {"inputs": ["insan", "insan"], "desc": "Sevgi ve kan bağıyla bir araya gelmiş toplumun en küçük yapı taşı."},
        "kabile": {"inputs": ["aile", "cadir"], "desc": "Aynı kökten gelen insanların oluşturduğu dayanışma topluluğu."},
        "koy": {"inputs": ["ev", "ev"], "desc": "Kırsal alanda tarım ve hayvancılıkla geçinen şirin yerleşim birimi."},
        "kasaba": {"inputs": ["koy", "pazar"], "desc": "Köyden büyük, çarşısı ve zanaatkarları olan küçük kentsel yerleşim."},
        "sehir": {"inputs": ["kasaba", "kale"], "desc": "Geniş caddeleri, fabrikaları ve binalarıyla büyük medeniyet merkezi."},
        "metropol": {"inputs": ["sehir", "sehir"], "desc": "Milyonlarca insanın yaşadığı küresel çapta devasa mega kent."},
        "krallik": {"inputs": ["sehir", "kral"], "desc": "Bir hükümdarın egemenliği altında yönetilen geniş topraklar."},
        "imparatorluk": {"inputs": ["krallik", "ordu"], "desc": "Birçok milleti ve kıtayı tek çatı altında toplayan dev imparatorluk."},
        "i_mparatorluk": {"inputs": ["krallik", "ordu"], "desc": "Birçok milleti ve kıtayı tek çatı altında toplayan dev imparatorluk."},
        "medeniyet": {"inputs": ["sehir", "yazi"], "desc": "Kültür, bilim, hukuk ve sanatın ulaştığı en yüksek toplumsal düzey."},
        "ev": {"inputs": ["tugla", "odun"], "desc": "İnsanların barınıp huzurla yaşadığı duvarlı ve çatılı yuva."},
        "kulube": {"inputs": ["odun", "ot"], "desc": "Orman içinde veya dağ başında ahşaptan yapılmış mütevazı barınak."},
        "cadir": {"inputs": ["kumas", "odun"], "desc": "Göçebelerin ve kaşiflerin kolayca kurup topladığı portatif kumaş barınak."},
        "saray": {"inputs": ["mermer", "altin"], "desc": "Kralların ve hükümdarların yaşadığı sütunlu görkemli anıtsal yapı."},
        "kale": {"inputs": ["tas", "duvar"], "desc": "Düşman saldırılarına karşı şehri koruyan mazgallı sağlam taş hisar."},
        "kule": {"inputs": ["tas", "kale"], "desc": "Uzakları gözetlemek veya savunmak için göğe yükselen silindirik taş yapı."},
        "gozetleme_kulesi": {"inputs": ["kule", "fener"], "desc": "Düşman hareketlerini erkenden fark etmek için kurulmuş yüksek gözetleme kulesi."},
        "sur": {"inputs": ["tas", "duvar"], "desc": "Şehrin etrafını çepeçevre saran yüksek ve kalın savunma duvarı."},
        "kopru": {"inputs": ["tas", "nehir"], "desc": "İki yakayı birbirine bağlayarak geçit veren kemerli köprü."},
        "liman": {"inputs": ["deniz", "tas"], "desc": "Gemilerin demirleyip yük indirip bindirdiği korunaklı kıyı tesisi."},
        "fener_kulesi": {"inputs": ["kule", "ates"], "desc": "Karanlık gecelerde denizdeki gemilere yol gösteren ışıklı deniz feneri."},
        "yol": {"inputs": ["tas", "toprak"], "desc": "Şehirleri ve köyleri birbirine bağlayan döşeli ulaşım şeridi."},
        "kaldirim": {"inputs": ["yol", "tas"], "desc": "Yayaların güvenle yürümesi için yol kenarına döşenmiş taş tabaka."},
        "tunel": {"inputs": ["dag", "kazma"], "desc": "Dağların altından delinerek açılan yeraltı geçiş koridoru."},
        "baraj": {"inputs": ["nehir", "beton"], "desc": "Nehir sularını tutarak enerji üreten ve su depolayan dev set."},
        "kanal": {"inputs": ["nehir", "kazma"], "desc": "Gemilerin geçmesi için kazılmış yapay su yolu."},
        "pazar": {"inputs": ["insan", "para"], "desc": "Tüccarların ürünlerini sergileyip halka sattığı hareketli çarşı."},
        "dukkan": {"inputs": ["ev", "pazar"], "desc": "Belirli ürünlerin satıldığı küçük ticarethane."},
        "banka": {"inputs": ["para", "altin"], "desc": "Paranın saklandığı, yatırıldığı ve kredi sağlanan finans kurumu."},
        "darphane": {"inputs": ["metal", "para"], "desc": "Devlet adına resmi altın ve madeni paraların basıldığı atölye."},
        "para": {"inputs": ["altin", "damga"], "desc": "Ticarette malların değerini belirleyen ve takası sağlayan resmi araç."},
        "altin_sikke": {"inputs": ["altin", "darphane"], "desc": "Üzerinde hükümdar mührü taşıyan saf altın para."},
        "kagit_para": {"inputs": ["kagit", "damga"], "desc": "Merkez bankası güvencesiyle basılan hafif ve değerli banknot."},
        "borsa": {"inputs": ["para", "pazar"], "desc": "Hisse senetlerinin ve kıymetli madenlerin alınıp satıldığı finans piyasası."},
        "okul": {"inputs": ["ev", "ogretmen"], "desc": "Çocukların ve gençlerin bilgi ve beceri edindiği eğitim yuvası."},
        "kutuphane": {"inputs": ["kitap", "ev"], "desc": "Binlerce cilt kitabın korunduğu sessiz bilgi mabedi."},
        "kitap": {"inputs": ["kagit", "yazi"], "desc": "Ciltlenmiş sayfalarıyla insanlığın hafızasını taşıyan yazılı eser."},
        "parsomen": {"inputs": ["deri", "yazi"], "desc": "İşlenmiş hayvan derisinden hazırlanan dayanıklı kadim yazı rulosu."},
        "buyu_parsomeni": {"inputs": ["parsomen", "buyu"], "desc": "Üzerinde efsunlu sözler yazılı kadim büyü parşömeni."},
        "murekkep": {"inputs": ["komur", "su"], "desc": "Kömür karası ve sudan yapılan yazı yazma sıvısı."},
        "kalem": {"inputs": ["kus_tuyu", "murekkep"], "desc": "Düşünceleri kağıda dökmek için kullanılan yazı aleti."},
        "yazi": {"inputs": ["kalem", "kagit"], "desc": "Konuşulan dili simgelerle kalıcı kılan medeniyet icadı."},
        "alfabe": {"inputs": ["yazi", "yazi"], "desc": "Bir dilin tüm seslerini temsil eden harfler dizgesi."},
        "matbaa": {"inputs": ["pres", "yazi"], "desc": "Kitapların binlerce nüsha halinde hızlıca basılmasını sağlayan devrim."},
        "gazete": {"inputs": ["matbaa", "kagit"], "desc": "Günün haberlerini halka ulaştıran günlük basılı yayın."},
        "harita": {"inputs": ["kagit", "pusula"], "desc": "Yeryüzü şekillerini ve sınırları gösteren coğrafi çizim."},
        "muze": {"inputs": ["ev", "fosil"], "desc": "Tarihi eserlerin ve sanat harikalarının sergilendiği kültür kurumu."},
        "tiyatro": {"inputs": ["sahne", "oyuncu"], "desc": "İnsan hikayelerinin canlı olarak sahnede sergilendiği dramatik sanat."},
        "muzik": {"inputs": ["ses", "ritim"], "desc": "Seslerin uyumuyla ruhu besleyen evrensel sanat dalı."},
        "flut": {"inputs": ["bambu", "hava"], "desc": "Üflenerek çalınan dinlendirici sesli ahşap nefesli çalgı."},
        "davul": {"inputs": ["deri", "odun"], "desc": "Gerilmiş deriye tokmakla vurularak çalınan ritim çalgısı."},
        "gitar": {"inputs": ["odun", "ip"], "desc": "Tellerine parmakla dokunularak çalınan melodik çalgı."},
        "piyano": {"inputs": ["disli", "muzik"], "desc": "Tuşlarına basıldığında tellere vuran çekiçlerle çalan zarif enstrüman."},
        "resim": {"inputs": ["kumas", "boya"], "desc": "Fırça ve renklerle tuvale yansıtılan görsel sanat eseri."},
        "tablo": {"inputs": ["resim", "cerceve"], "desc": "Çerçevelenerek duvara asılmış değerli sanat eseri."},
        "heykel": {"inputs": ["mermer", "cekic"], "desc": "Mermer veya taşa çekiçle form verilerek yapılan 3D sanat eseri."},
        "araba": {"inputs": ["tekerlek", "at"], "desc": "Atların çektiği veya motorla çalışan tekerlekli kara taşıtı."},
        "fayton": {"inputs": ["araba", "at"], "desc": "Dört tekerlekli, körüklü ve atlı zarif gezinti arabası."},
        "bisiklet": {"inputs": ["tekerlek", "zincir"], "desc": "İki tekerlek üzerinde pedal çevirerek sürülen insan gücüyle çalışan araç."},
        "motosiklet": {"inputs": ["bisiklet", "motor"], "desc": "İki tekerlekli ve motor gücüyle çalışan hızlı kara taşıtı."},
        "otomobil": {"inputs": ["araba", "icten_yanmali_motor"], "desc": "Dört tekerlekli motorlu modern kişisel yolcu taşıtı."},
        "kamyon": {"inputs": ["otomobil", "demir"], "desc": "Ağır yükleri ve ticari malları şehirlerarası taşıyan büyük taşıt."},
        "tren": {"inputs": ["lokomotif", "vagon"], "desc": "Raylar üzerinde birbirine bağlı vagonları çeken katar."},
        "lokomotif": {"inputs": ["buhar_motoru", "tekerlek"], "desc": "Raylar üstündeki treni çeken güçlü buharlı veya elektrikli çekici."},
        "demiryolu": {"inputs": ["demir", "yol"], "desc": "Trenlerin üzerinde hızla kayarak ilerlediği paralel çelik ray hattı."},
        "sal": {"inputs": ["odun", "ip"], "desc": "Birbirine bağlanmış kütüklerden yapılan en ilkel su taşıtı."},
        "kano": {"inputs": ["odun", "kurek"], "desc": "İçi oyulmuş ağaç gövdesinden yapılan hafif nehir teknesi."},
        "yelkenli": {"inputs": ["gemi", "kumas"], "desc": "Rüzgarı yelkenlerine doldurarak denizleri aşan tekne."},
        "kadirga": {"inputs": ["gemi", "kurek"], "desc": "Hem kürekle hem yelkenle yürütülen tarihi savaş gemisi."},
        "buharli_gemi": {"inputs": ["gemi", "buhar_motoru"], "desc": "Buhar çarklarıyla dalgaları yaran okyanus gemisi."},
        "denizalti": {"inputs": ["gemi", "su"], "desc": "Su altında kilometrelerce derinlikte görünmeden ilerleyen çelik gemi."},
        "zirhli_gemi": {"inputs": ["gemi", "celik"], "desc": "Gövdesi kalın çelik levhalarla kaplı ağır savaş zırhlısı."},
        "ucurtma": {"inputs": ["kagit", "ruzgar"], "desc": "İnce bir iple gökyüzünde rüzgara karşı süzülen renkli oyuncak."},
        "sicak_hava_balonu": {"inputs": ["kumas", "ates"], "desc": "İçindeki havanın ateşle ısıtılmasıyla göğe yükselen dev balon."},
        "zeplin": {"inputs": ["sicak_hava_balonu", "motor"], "desc": "Gazla dolu dev gövdesi ve pervaneleriyle uçan güdümlü hava gemisi."},
        "ucak": {"inputs": ["zeplin", "icten_yanmali_motor"], "desc": "Sabit kanatları ve güçlü motorlarıyla bulutları yaran hızlı hava taşıtı."},
        "helikopter": {"inputs": ["ucak", "pervane"], "desc": "Tepesindeki dönen pervanesi sayesinde dikey iniş-kalkış yapabilen hava aracı."},
        "duvar": {"inputs": ["tugla", "harc"], "desc": "Tuğla ve harcın örülmesiyle dikilen sağlam ayırıcı yapı."},
        "tugla_duvar": {"inputs": ["tugla", "harc"], "desc": "Kırmızı tuğlalarla örülmüş sağlam bina duvarı."},
        "demir_parmaklik": {"inputs": ["demir", "civi"], "desc": "Güvenlik veya hapis amacıyla döşenmiş demir çubuk kafes."},
        "kale_kapisi": {"inputs": ["kale", "demir"], "desc": "Kalenin girişini koruyan devasa demir takviyeli meşe kapı."},

        # 9. Aşama: Mistik, Mitoloji, Evren & Kozmoloji
        "evren": {"inputs": ["galaksi", "karadelik"], "desc": "Tüm maddeyi, enerjiyi, zamanı ve mekanı içinde barındıran sonsuz bütün."},
        "galaksi": {"inputs": ["yildiz", "karadelik"], "desc": "Milyarlarca yıldız ve gezegen sisteminin döndüğü dev kozmik ada."},
        "nebula": {"inputs": ["yildiz_tozu", "gaz"], "desc": "Yeni yıldızların doğduğu renkli ve ışıldayan dev kozmik gaz bulutu."},
        "yildiz": {"inputs": ["ates", "plazma"], "desc": "Çekirdeğinde nükleer füzyon gerçekleşen dev akkor plazma küresi."},
        "minyatur_yildiz": {"inputs": ["yildiz", "buyu"], "desc": "Simyacının kristal fanus içinde hapsettiği cüce parlak yıldız."},
        "yildiz_tozu": {"inputs": ["yildiz", "ruzgar"], "desc": "Süpernova patlamalarından evrene yayılan kadim element tozu."},
        "gunes": {"inputs": ["yildiz", "isik"], "desc": "Gündüzleri dünyamızı aydınlatan ve yaşam veren ana yıldızımız."},
        "ay": {"inputs": ["tas", "gece"], "desc": "Dünyanın uydusu olan ve geceleri güneş ışığını yansıtan gümüş gökcismi."},
        "gezegen": {"inputs": ["tas", "gunes"], "desc": "Bir yıldızın etrafındaki yörüngede dönen büyük gök cismi."},
        "asteroit": {"inputs": ["tas", "uzay"], "desc": "Uzay boşluğunda serbestçe sürüklenen devasa kaya parçası."},
        "meteor": {"inputs": ["asteroit", "atmosfer"], "desc": "Dünya atmosferine girip sürtünmeyle alev alan kayan yıldız taşı."},
        "kuyruklu_yildiz": {"inputs": ["buz", "yildiz"], "desc": "Güneşe yaklaştıkça arkasında milyonlarca kilometrelik gaz kuyruğu bırakan gökcismi."},
        "karadelik": {"inputs": ["yildiz", "cekim"], "desc": "Işığın dahi kaçamayacağı kadar güçlü bir yerçekimine sahip kozmik tekillik."},
        "zaman": {"inputs": ["kum_saati", "evren"], "desc": "Olayların geçmişten geleceğe aktığı dördüncü boyut akışı."},
        "zaman_kum_saati": {"inputs": ["kum_saati", "zaman"], "desc": "İçindeki tanelerle zamanı bükebilen büyülü kum saati."},
        "uzay": {"inputs": ["gece", "evren"], "desc": "Gök cisimleri arasındaki sonsuz karanlık ve sessiz boşluk."},
        "gece": {"inputs": ["golge", "dunya"], "desc": "Güneşin ufkun ardına geçmesiyle yeryüzünü saran karanlık örtü."},
        "gunduz": {"inputs": ["gunes", "isik"], "desc": "Güneşin doğmasıyla başlayan aydınlık ve hareketli zaman dilimi."},
        "safak": {"inputs": ["gece", "isik"], "desc": "Güneş doğmadan hemen önce ufkun kızıla boyandığı an."},
        "alacakaranlik": {"inputs": ["gunduz", "gece"], "desc": "Gündüzün geceye, ışığın karanlığa kavuştuğu loş an."},
        "tutulma": {"inputs": ["gunes", "ay"], "desc": "Ayın dünya ile güneş arasına girip gündüzü karartması."},
        "buyu": {"inputs": ["enerji", "yasam"], "desc": "Doğaüstü iradeyle fizik kanunlarını bükme ve yaratma kudreti."},
        "mana": {"inputs": ["enerji", "buyu"], "desc": "Büyücülerin büyü yaparken tükettiği saf ruhani enerji havuzu."},
        "iksir": {"inputs": ["su", "buyu"], "desc": "Şifalı otların ve büyülü maddelerin kazanında kaynatılmış iksir."},
        "i_ksir": {"inputs": ["su", "buyu"], "desc": "Şifalı otların ve büyülü maddelerin kazanında kaynatılmış iksir."},
        "sifa_i_ksiri": {"inputs": ["iksir", "gul"], "desc": "Yaraları anında iyileştiren kırmızı renkli şifalı iksir."},
        "zehir": {"inputs": ["yilan", "sivi"], "desc": "Canlıların bedenini felç eden veya yok eden ölümcül toksin."},
        "zehirli_sivi": {"inputs": ["zehir", "su"], "desc": "Zehirli özlerin suyla karıştırılmış tehlikeli şişesi."},
        "zehir_sisesi": {"inputs": ["zehir", "sise"], "desc": "Üzerinde kurukafa işareti olan ölümcül zehir dolu cam şişe."},
        "tilsim": {"inputs": ["metal", "buyu"], "desc": "Üzerine koruyucu büyüler kazınmış kutsal metal takı."},
        "muska": {"inputs": ["deri", "buyu"], "desc": "Kötülüklerden ve nazardan koruduğuna inanılan boyuna asılan koruyucu nesne."},
        "asa": {"inputs": ["odun", "kristal"], "desc": "Büyü enerjisini odaklayıp fırlatmaya yarayan sihirli değnek."},
        "run": {"inputs": ["tas", "buyu"], "desc": "Kadim taşlara kazınmış gizemli ve güçlü büyü harfi."},
        "portal_runu": {"inputs": ["run", "boyut_kapisi"], "desc": "Mekanlar arası anlık geçit açan büyülü portal rünü."},
        "buz_runu": {"inputs": ["run", "buz"], "desc": "Dokunduğu her şeyi anında donduran buz rünü taşı."},
        "simya": {"inputs": ["bilim", "buyu"], "desc": "Değersiz metalleri altına, maddeleri ebediyete dönüştürme kadim sanatı."},
        "felsefe_tasi": {"inputs": ["simya", "elmas"], "desc": "Her şeyi altına çeviren ve ölümsüzlük bahşeden efsanevi simya taşı."},
        "olumsuzluk_i_ksiri": {"inputs": ["felsefe_tasi", "iksir"], "desc": "İçene ebedi gençlik ve sonsuz ömür sunan iksirlerin iksiri."},
        "hayalet": {"inputs": ["ruh", "gece"], "desc": "Bu dünyadan ayrılamamış ölülerin yarı saydam silueti."},
        "ruh": {"inputs": ["yasam", "isik"], "desc": "Beden öldükten sonra yaşamaya devam eden saf bilinç özü."},
        "zombi": {"inputs": ["insan", "olum"], "desc": "Büyüyle mezarından kaldırılmış bilinci olmayan yaşayan ölü."},
        "vampir": {"inputs": ["insan", "kan"], "desc": "Geceleri kanla beslenen, güneş ışığına çıkamayan ölümsüz varlık."},
        "kurt_adam": {"inputs": ["insan", "dolunay"], "desc": "Dolunay çıktığında vahşi bir kurda dönüşen lanetli insan."},
        "gulyabani": {"inputs": ["hayalet", "cadir"], "desc": "Karanlık çöllerde ve harabelerde dolaşan hortlak varlık."},
        "golem": {"inputs": ["camur", "buyu"], "desc": "Çamur veya taştan yapılıp büyüyle canlandırılmış dev yapay muhafız."},
        "pegasus": {"inputs": ["at", "kus_tuyu"], "desc": "Sırtındaki bembeyaz kanatlarıyla göklerde uçan efsanevi at."},
        "anka_kusu": {"inputs": ["kus", "ates"], "desc": "Küllerinden yeniden doğan ebedi ateş kuşu Simurg."},
        "anka_kulu": {"inputs": ["anka_kusu", "ates"], "desc": "Anka kuşunun yanıp kül olduğunda bıraktığı yeniden doğuş tozu."},
        "grifon": {"inputs": ["aslan", "kartal"], "desc": "Gövdesi aslan, başı ve kanatları kartal olan cesur mitolojik yaratık."},
        "kentaurluk": {"inputs": ["insan", "at"], "desc": "Gövdesi insan, altı at olan efsanevi orman savaşçısı ırk."},
        "peri": {"inputs": ["insan", "kelebek"], "desc": "Kelebek kanatlarıyla doğayı koruyan minik ve sevimli büyü varlığı."},
        "cin": {"inputs": ["ates", "hava"], "desc": "Dumansız ve kızgın ateşten yaratılmış görünmez mistik varlık."},
        "seytan": {"inputs": ["cin", "karanlik"], "desc": "Kibri yüzünden lanetlenmiş, insanları yoldan çıkaran karanlık güç."},
        "melek": {"inputs": ["ruh", "isik"], "desc": "Saf ışıktan yaratılmış, ilahi emirleri yerine getiren masum varlık."},
        "tanri": {"inputs": ["evren", "yasam"], "desc": "Tüm kainatın ve varlığın yaratıcısı olan yüce ilahi kudret."},
        "tapinak": {"inputs": ["saray", "tanri"], "desc": "İbadet etmek ve tanrılara adak adamak için inşa edilen kutsal yapı."},
        "altar": {"inputs": ["tas", "tapinak"], "desc": "Tapınakların kalbinde adakların sunulduğu kutsal kurban masası."},
        "kutsal_kase": {"inputs": ["altin", "olumsuzluk_i_ksiri"], "desc": "İçenlere ebedi hayat bahşettiği söylenen efsanevi kase."},
        "totem": {"inputs": ["odun", "ruh"], "desc": "Kabilenin atalarını ve koruyucu ruhlarını simgeleyen oymalı ahşap sütun."},
        "piramit": {"inputs": ["tas", "mezar"], "desc": "Firavunların ebedi istirahatgahı olan devasa geometrik anıt mezar."},
        "sfenks": {"inputs": ["heykel", "aslan"], "desc": "Piramitleri bekleyen insan başlı dev aslan heykeli."},
        "obelisk": {"inputs": ["tas", "anit"], "desc": "Güneş ışınlarını simgeleyen tek parça dikilitaş anıtı."},
        "anit": {"inputs": ["heykel", "tarih"], "desc": "Önemli olayları ve kahramanları ölümsüzleştiren anıt yapı."},
        "hazine": {"inputs": ["altin", "sandik"], "desc": "Sandıklar dolusu altın, elmas ve mücevherden oluşan zenginlik."},
        "kayip_sehir": {"inputs": ["sehir", "orman"], "desc": "Zamanın ve bitki örtüsünün yuttuğu kadim harabe uygarlık."},
        "boyut_kapisi": {"inputs": ["portal_runu", "uzay"], "desc": "Farklı evrenlere ve boyutlara açılan devasa kozmik solucan deliği geçidi."},
        "yildiz_gecidi_cekirdegi": {"inputs": ["boyut_kapisi", "enerji"], "desc": "Yıldız geçidini sonsuz enerjiyle besleyen reaktör çekirdeği."},
        "cehennem_tasi": {"inputs": ["tas", "lav"], "desc": "Yeraltının lav ateşini içinde hapseden korlaşmış cehennem taşı."},
        "kahin_kuresi": {"inputs": ["kristal", "kahin"], "desc": "Geleceği ve kaderin sırlarını gösteren parıldayan kristal küre."},
        "kozmik_usturlap": {"inputs": ["pusula", "yildiz"], "desc": "Yıldızların ve gezegenlerin konumunu hesaplayan antika astronomik cihaz."},
        "runik_zirh": {"inputs": ["demir_zirh", "run"], "desc": "Üzerine koruyucu büyülü rünler kazınmış kırılmaz runik zırh."},
        "meka_zirhi": {"inputs": ["robot", "zirh"], "desc": "İnsanın içine girip devasa güç kazandığı hidrolik meka dış iskeleti."},
        "ates_topu_kitabi": {"inputs": ["kitap", "ates"], "desc": "Düşmanlara alev topu yağdırmayı öğreten simya büyü kitabı."},
        "i_lluzyon_aynasi": {"inputs": ["ayna", "buyu"], "desc": "Bakan kişiye farklı yanılsamalar gösteren büyülü illüzyon aynası."},
        "i_ksir_kazani": {"inputs": ["kazan", "iksir"], "desc": "Fokurdayan büyülü karışımların hazırlandığı mistik kazan."},
        "i_nci": {"inputs": ["istiridye", "kum"], "desc": "İstiridyenin içine kaçan kum tanesini kaplayarak oluşturduğu değerli inci."},
        "bosluk_sisesi": {"inputs": ["sise", "uzay"], "desc": "İçinde mutlak uzay boşluğunu hapseden gizemli cam fanus."},
    }

    return recipes

print("Crafting recipe definition template prepared.")
